FROM amazoncorretto:25.0.1 AS build
WORKDIR /app
COPY . .
RUN ./gradlew bootJar -x test --no-daemon

FROM amazoncorretto:25.0.1
WORKDIR /app
COPY --from=build /app/build/libs/AuthService-*-RELEASE.jar app.jar
CMD ["java", "-jar", "app.jar", "--spring.profiles.active=docker"]